name: portfolio
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.2.1
  url_launcher: ^6.1.6
  syncfusion_flutter_pdfviewer: ^20.3.50
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.13
  velocity_x: ^3.6.0
  vertical_card_pager: ^1.5.0
  flutter_carousel_slider: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/MostafaMahmoudcv.pdf
    - assets/lang/

  fonts:

    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoCondensed.ttf